apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::287223951807:role/eksctl-RoboShop-dev-addon-iamserviceaccount-r-Role1-Q2TyjGOdBNyb
  creationTimestamp: "2026-01-12T20:29:40Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: pass-secret
  namespace: roboshop
  # resourceVersion: "20800"
  # uid: 61ce2aea-fc7c-4bcb-a644-0cd3b1445bf9
  
